---
- id: extract-vba-code
  name: Extract VBA code from Excel files
  description: Extracts VBA code from Excel files and saves it in a specified directory.
  entry: pre-commit-vba
  args: [extract]
  language: python
  files: \.xlsm$|\.xlsb$|\.xls$
  exclude: ^(?!.*\.(xlsm|xlsb|xls)$).*$
- id: check-excel-book-version
  name: Check Excel book version
  description: Checks the version of Excel books to ensure compatibility.
  entry: pre-commit-vba
  args: [check]
  language: python
  always_run: true
